### ISSUE TITLE
Dereference command not working on windows 

### ISSUE THREAD

**Issue by MitchellNeill** [kstasik/schema-tools#63]
I tried using the dereference command on windows and it failed to load the source file. 
I attempt to run the tests using, cargo test --workspace --exclude test_discover_git_hash 

The below are the test result failures.

~~~

failures:

---- process::dereference::tests::test_simple_with_external_reference stdout ----
thread 'process::dereference::tests::test_simple_with_external_reference' panicked at 'called `Result::unwrap()` on an `Err` value: SchemaLoad { url: "file:///C:/Users/MitchellNeill/code/schema-tools/resources/test/json-schemas/03-simple-with-external-ref.json" }', src\process\dereference.rs:208:31

---- process::dereference::tests::test_create_internal_references stdout ----
thread 'process::dereference::tests::test_create_internal_references' panicked at 'called `Result::unwrap()` on an `Err` value: SchemaLoad { url: "file:///C:/Users/MitchellNeill/code/schema-tools/resources/test/json-schemas/20-local-reference.json" }', src\process\dereference.rs:208:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- process::dereference::tests::test_infinite_ref stdout ----
thread 'process::dereference::tests::test_infinite_ref' panicked at 'called `Result::unwrap()` on an `Err` value: SchemaLoad { url: "file:///C:/Users/MitchellNeill/code/schema-tools/resources/test/json-schemas/07-with-infinite-ref.json" }', src\process\dereference.rs:208:31
note: panic did not contain expected string
      panic message: `"called `Result::unwrap()` on an `Err` value: SchemaLoad { url: \"file:///C:/Users/MitchellNeill/code/schema-tools/resources/test/json-schemas/07-with-infinite-ref.json\" }"`,
 expected substring: `"Infinite reference occured!"`
---- process::dereference::tests::test_simple_with_reference stdout ----
thread 'process::dereference::tests::test_simple_with_reference' panicked at 'called `Result::unwrap()` on an `Err` value: SchemaLoad { url: "file:///C:/Users/MitchellNeill/code/schema-tools/resources/test/json-schemas/02-simple-with-reference.json" }', src\process\dereference.rs:208:31

---- process::dereference::tests::test_string_reference stdout ----
thread 'process::dereference::tests::test_string_reference' panicked at 'called `Result::unwrap()` on an `Err` value: SchemaLoad { url: "file:///C:/Users/MitchellNeill/code/schema-tools/resources/test/json-schemas/16-string-reference.json" }', src\process\dereference.rs:208:31

---- process::dereference::tests::test_skip_references stdout ----
thread 'process::dereference::tests::test_skip_references' panicked at 'called `Result::unwrap()` on an `Err` value: SchemaLoad { url: "file:///C:/Users/MitchellNeill/code/schema-tools/resources/test/json-schemas/05-with-nested-remote-external-ref.json" }', src\process\dereference.rs:208:31

---- process::dereference::tests::test_with_local_reference stdout ----
thread 'process::dereference::tests::test_with_local_reference' panicked at 'called `Result::unwrap()` on an `Err` value: SchemaLoad { url: "file:///C:/Users/MitchellNeill/code/schema-tools/resources/test/json-schemas/06-with-local-reference.json" }', src\process\dereference.rs:208:31

---- process::dereference::tests::test_with_nested_remote_external_reference stdout ----
thread 'process::dereference::tests::test_with_nested_remote_external_reference' panicked at 'called `Result::unwrap()` on an `Err` value: SchemaLoad { url: "file:///C:/Users/MitchellNeill/code/schema-tools/resources/test/json-schemas/05-with-nested-remote-external-ref.json" }', src\process\dereference.rs:208:31

---- discovery::tests::test_discover_git_tag_return_already_existing_registry stdout ----
thread 'discovery::tests::test_discover_git_tag_return_already_existing_registry' panicked at 'called `Result::unwrap()` on an `Err` value: GitDiscoveryError(Error { code: -1, klass: 2, message: "failed to make directory 'C:\\Users\\MITCHE~1\\AppData\\Local\\Temp\\schema-tools\\09d3c94802a3e4e23407ad008cf8819f': The system cannot find the path specified.\r\n" })', src\discovery.rs:359:10

---- discovery::tests::test_discovery_git_inherit_templates stdout ----
thread 'discovery::tests::test_discovery_git_inherit_templates' panicked at 'called `Result::unwrap()` on an `Err` value: GitDiscoveryError(Error { code: -1, klass: 2, message: "failed to make directory 'C:\\Users\\MITCHE~1\\AppData\\Local\\Temp\\schema-tools\\96eaab5eba0a59749f7ba79f7c7c6efa': The system cannot find the path specified.\r\n" })', src\discovery.rs:181:10

---- discovery::tests::test_discover_git_branch stdout ----
thread 'discovery::tests::test_discover_git_branch' panicked at 'called `Result::unwrap()` on an `Err` value: GitDiscoveryError(Error { code: -1, klass: 2, message: "failed to make directory 'C:\\Users\\MITCHE~1\\AppData\\Local\\Temp\\schema-tools\\ade8f19c191c650073e470beee65c3e1': The system cannot find the path specified.\r\n" })', src\discovery.rs:281:10

---- discovery::tests::test_discovery_git_inherit stdout ----
thread 'discovery::tests::test_discovery_git_inherit' panicked at 'called `Result::unwrap()` on an `Err` value: GitDiscoveryError(Error { code: -1, klass: 2, message: "failed to make directory 'C:\\Users\\MITCHE~1\\AppData\\Local\\Temp\\schema-tools\\96eaab5eba0a59749f7ba79f7c7c6efa': The system cannot find the path specified.\r\n" })', src\discovery.rs:210:10

---- discovery::tests::test_discover_git_hash stdout ----
thread 'discovery::tests::test_discover_git_hash' panicked at 'called `Result::unwrap()` on an `Err` value: GitDiscoveryError(Error { code: -1, klass: 2, message: "failed to make directory 'C:\\Users\\MITCHE~1\\AppData\\Local\\Temp\\schema-tools\\96eaab5eba0a59749f7ba79f7c7c6efa': The system cannot find the path specified.\r\n" })', src\discovery.rs:266:10

---- discovery::tests::test_discover_git_tag stdout ----
thread 'discovery::tests::test_discover_git_tag' panicked at 'called `Result::unwrap()` on an `Err` value: GitDiscoveryError(Error { code: -1, klass: 2, message: "failed to make directory 'C:\\Users\\MITCHE~1\\AppData\\Local\\Temp\\schema-tools\\aa2e6641106ed92dbc78bdfcefa6cd9a': The system cannot find the path specified.\r\n" })', src\discovery.rs:321:10

---- discovery::tests::test_discovery_git stdout ----
thread 'discovery::tests::test_discovery_git' panicked at 'called `Result::unwrap()` on an `Err` value: GitDiscoveryError(Error { code: -1, klass: 2, message: "failed to make directory 'C:\\Users\\MITCHE~1\\AppData\\Local\\Temp\\schema-tools\\96eaab5eba0a59749f7ba79f7c7c6efa': The system cannot find the path specified.\r\n" })', src\discovery.rs:236:10

---- discovery::tests::test_discover_git_tag_clean_existing_registry stdout ----
thread 'discovery::tests::test_discover_git_tag_clean_existing_registry' panicked at 'called `Result::unwrap()` on an `Err` value: GitDiscoveryError(Error { code: -1, klass: 2, message: "failed to make directory 'C:\\Users\\MITCHE~1\\AppData\\Local\\Temp\\schema-tools\\aca92f409cf5201026fca825a5fd96ca': The system cannot find the path specified.\r\n" })', src\discovery.rs:383:10

---- process::name::tests::test_simple_openapi_naming stdout ----
thread 'process::name::tests::test_simple_openapi_naming' panicked at 'called `Result::unwrap()` on an `Err` value: SchemaLoad { url: "file:///C:/Users/MitchellNeill/code/schema-tools/resources/test/openapi/01-simple.yaml" }', src\process\name\mod.rs:17:31

---- resolver::tests::test_when_file_and_spec_are_valid stdout ----
thread 'resolver::tests::test_when_file_and_spec_are_valid' panicked at 'assertion failed: `(left == right)`
  left: `false`,
 right: `true`', src\resolver.rs:159:9

---- schema::tests::test_string_to_url_should_correctly_convert_absolute_existing_path_to_url stdout ----
thread 'schema::tests::test_string_to_url_should_correctly_convert_absolute_existing_path_to_url' panicked at 'assertion failed: `(left == right)`
  left: `false`,
 right: `true`', src\schema.rs:209:9

---- schema::tests::test_when_file_and_spec_are_valid stdout ----
thread 'schema::tests::test_when_file_and_spec_are_valid' panicked at 'assertion failed: `(left == right)`
  left: `false`,
 right: `true`', src\schema.rs:185:9

---- discovery::tests::test_discovery_file stdout ----
thread 'discovery::tests::test_discovery_file' panicked at 'assertion failed: `(left == right)`
  left: `false`,
 right: `true`', src\discovery.rs:253:9


failures:
    discovery::tests::test_discover_git_branch
    discovery::tests::test_discover_git_hash
    discovery::tests::test_discover_git_tag
    discovery::tests::test_discover_git_tag_clean_existing_registry
    discovery::tests::test_discover_git_tag_return_already_existing_registry
    discovery::tests::test_discovery_file
    discovery::tests::test_discovery_git
    discovery::tests::test_discovery_git_inherit
    discovery::tests::test_discovery_git_inherit_templates
    process::dereference::tests::test_create_internal_references
    process::dereference::tests::test_infinite_ref
    process::dereference::tests::test_simple_with_external_reference
    process::dereference::tests::test_simple_with_reference
    process::dereference::tests::test_skip_references
    process::dereference::tests::test_string_reference
    process::dereference::tests::test_with_local_reference
    process::dereference::tests::test_with_nested_remote_external_reference
    process::name::tests::test_simple_openapi_naming
    resolver::tests::test_when_file_and_spec_are_valid
    schema::tests::test_string_to_url_should_correctly_convert_absolute_existing_path_to_url
    schema::tests::test_when_file_and_spec_are_valid
~~~

**Comment by kstasik** [comment]
I added windows support but not sure if it's working correctly (i don't have access to windows and had to fix issues on github worker directly):

https://github.com/kstasik/schema-tools/releases/tag/v0.7.0
